# Generated by Django 5.0.3 on 2024-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
