# Generated by Django 5.0.3 on 2024-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_customer_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dname',
            field=models.CharField(max_length=50),
        ),
    ]
