# Generated by Django 5.0.3 on 2024-03-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cateid', models.AutoField(primary_key=True, serialize=False)),
                ('catename', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=60)),
                ('bprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bdes', models.CharField(max_length=300)),
                ('bavail', models.CharField(max_length=3)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.category')),
            ],
        ),
    ]
