# Generated by Django 5.0.3 on 2024-03-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_books_bauth'),
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=60)),
                ('bauthor', models.CharField(default=None, max_length=50)),
                ('bdescription', models.CharField(max_length=300)),
                ('bsem', models.IntegerField()),
                ('bcount', models.IntegerField()),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('odate', models.DateField()),
                ('duedate', models.DateField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
