# Generated by Django 5.0.3 on 2024-03-25 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_book_order_delete_books_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
